#!/bin/bash

# Slackware build script for Kong Arena
# Copyright Oct 2026 David Ferrone RI, USA
# All rights reserved.

# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=kongarena
SRC=KongArena-Linux-x64.tar.gz
VERSION=${VERSION:-0.31}

BUILD=${BUILD:-1}
TAG=${TAG:-_Zap}
PKGTYPE=${PKGTYPE:-tgz}
TMP=${TMP:-/tmp/Zap}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;; 
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

set -e
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

mkdir $PKG/opt
cp $SRC $PKG/opt
cd $PKG/opt
tar xf $SRC
rm $SRC
cd kong_arena

chown -R root:root .

find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;

chmod 755 KongArena
chmod 755 bin/dkwolf_linux

# /bin is mutable, app.dat is written here
chown root:users bin
chmod 2775 bin

for dir in inp queue session stream snap; do
    chown -R root:users "bin/$dir"
    find "bin/$dir" -type d -exec chmod 2775 {} \;
    find "bin/$dir" -type f -exec chmod 664 {} \;
done

chown -R root:root bin/roms
find bin/roms -type d -exec chmod 755 {} \;
find bin/roms -type f -exec chmod 644 {} \;


mkdir -p $PKG/usr $PKG/usr/doc $PKG/usr/games
mkdir -p $PKG/usr/share $PKG/usr/share/applications
cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

cat $CWD/$PRGNAM > $PKG/usr/games/$PRGNAM
chmod 755 $PKG/usr/games/$PRGNAM

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
